server:
 port:9000
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  #实体类所做包
  type-aliases-package: cn.mldn.vo
  #mapper.xml所在位置
  mapper-locations: 
  - classpath:mybatis/mapper/**/*.xml
spring:
  #数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/mldn8001
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true  
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-mills: 200
   



   

